version: "3.8"
services:
  mysqldb:
    image: mysql:8.0
    container_name: mysql2
    environment:
      MYSQL_ROOT_PASSWORD: admin1234
      MYSQL_DATABASE: empldb
      MYSQL_USER: root
      MYSQL_PASSWORD: admin1234
    ports:
       - "3306:3306"
       - "33060:33060"
    volumes:
      - ./db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - emplnetwork
  empl1:
    image: emplz
    container_name: empl_1
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/empldb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin1234
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    networks:
      emplnetwork:
networks:
  emplnetwork:
    driver: bridge
